version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swapi
      MYSQL_USER: swapiuser
      MYSQL_PASSWORD: swapipassword
    ports:
      - '3306:3306'

  php:
    container_name: php
    build:
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/laravel-swapi-project
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www//laravel-swapi-project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database  
